name: Release
on:
  push:
    branches:
      - master
      - dev
      - qa
jobs:
  checkout:
    name: Checkout
    runs-on: self-hosted
    container: 
      image: node:16
      options: --user 1000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  build:
    name: Build Docker Image
    runs-on: self-hosted
    needs: [checkout]
    container: 
      image: gcr.io/kaniko-project/executor:debug
      options: --user 1000
    steps:
      - name: Build image
        run: /kaniko/executor --context . --dockerfile Dockerfile --no-push
      - name: Echo 
        run: echo test > test

  release:
    name: Release
    runs-on: self-hosted
    needs: [build]
    container: 
      image: node:16
      options: --user 1000
    steps:
      - name: List
        run: ls -al
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17'
      - name: Install dependencies
        run: npm i --legacy-peer-deps
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Check version
        run: cat version || exit 1