name: Release
on:
  push:
    branches:
      - master
      - dev
      - qa
jobs:
  release:
    name: Release
    runs-on: self-hosted
    container: node:16
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm i --legacy-peer-deps
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Check version
        run: cat version || exit 1

  build:
    name: Build Docker Image
    runs-on: self-hosted
    container: gcr.io/kaniko-project/executor:debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run:  /kaniko/executor --context . --dockerfile Dockerfile --no-push
